apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: 10.10.1.34:30500/local-nodejs-mariadb # mariadb
        imagePullPolicy: Always
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: adt-auth
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: adt-config
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: adt-config
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: DB_DATABASE
              name: adt-config
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 2
            memory: 8Gi
          requests:
            cpu: 1
            memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: users-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: users
